# Copy this file to another location and modify as necessary.
version: '3'
services:
  app:
    ##pull an image from github docker registry
    image: ghcr.io/imihalcea/rudolfs:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - data:/data
    restart: always
    environment:
      - LFS_ENCRYPTION_KEY
      - LFS_S3_BUCKET
      - LFS_MAX_CACHE_SIZE
    entrypoint:
      - /tini
      - --
      - /rudolfs
      - --port
      - 9999
      - --cache-dir
      - /data
      - --key
      - ${LFS_ENCRYPTION_KEY}
      - --max-cache-size
      - ${LFS_MAX_CACHE_SIZE}
      - s3
      - --bucket
      - ${LFS_S3_BUCKET}

volumes:
  data:
